# Generated by Django 5.1.15 on 2026-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("composer", "0020_platformpost_first_comment_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformpost",
            name="metrics_gone_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When analytics sync learned this post's remote object no longer exists. Excluded from future metric syncs once set.",
                null=True,
            ),
        ),
    ]
