# Generated by Django 5.1.15 on 2026-09-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0022_alter_post_origin'),
        ('composer', '0022_platformpost_analytics_column_defaults'),
    ]

    operations = [
    ]
