# Generated by Django 5.1.15 on 2026-10-09 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0003_apikeyauditlog_actor_label_apikeyauditlog_actor_user_and_more'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='rate_override_daily',
            field=models.PositiveIntegerField(blank=True, help_text='Calls-per-UTC-day override. Null = use platform default; 0 freezes the key.', null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rate_override_hourly',
            field=models.PositiveIntegerField(blank=True, help_text='Calls-per-UTC-hour override. Null = use platform default; 0 freezes the key.', null=True),
        ),
        migrations.CreateModel(
            name='ApiKeyUsageHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=64)),
                ('hour_start', models.DateTimeField(help_text='Start of the UTC hour this row counts.')),
                ('action', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField()),
                ('actor_user', models.ForeignKey(blank=True, help_text='Set for OAuth-authenticated MCP callers; null for key callers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_hourly', to=settings.AUTH_USER_MODEL)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_hourly', to='api_keys.apikey')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_hourly', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'api_keys_usage_hourly',
                'indexes': [models.Index(fields=['hour_start'], name='idx_usage_hour')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'hour_start', 'workspace', 'action', 'status_code'), name='uniq_usage_actor_hour_ws_action_status')],
            },
        ),
    ]
