# Generated by Django 5.1.15 on 2026-09-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_intelligence', '0002_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
    ]
