# Generated by Django 5.1.15 on 2026-04-15 23:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("composer", "0015_per_account_status"),
        ("social_accounts", "0003_add_instagram_personal_platform"),
        ("workspaces", "0002_replace_icon_url_with_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posts_fetched", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_logs",
                        to="social_accounts.socialaccount",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_logs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_refresh_log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PostSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform_post_id", models.CharField(max_length=255)),
                ("post_url", models.URLField(blank=True, default="", max_length=500)),
                ("post_text", models.TextField(blank=True, default="")),
                ("post_type", models.CharField(blank=True, default="", max_length=30)),
                ("posted_at", models.DateTimeField()),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("saves", models.IntegerField(default=0)),
                ("engagements", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_platform_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="composer.platformpost",
                    ),
                ),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_snapshots",
                        to="social_accounts.socialaccount",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_snapshots",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_post_snapshot",
                "ordering": ["-posted_at"],
                "unique_together": {("social_account", "platform_post_id")},
            },
        ),
    ]
